replicas:
- count: 1
  name: dummy-api
apiVersion: kustomize.config.k8s.io/v1beta1
patches:
- path: ingress-patch.yml
  target:
    kind: Ingress
    name: dummy-api

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - ./configs/.env
  - ./configs/config.yml
  name: dummy
  namespace: ki-prd-dummy

kind: Kustomization
namespace: ki-prd-dummy
resources:
- ../../application
images:
- name: cicd-image-place-holder
  newName: rm-bd-registry-01.bigdata.digikala.com/bigdata/karname/dummy-api
  newTag: 17692-master-c3d9ea37
- name: rm-bd-registry-01.bigdata.digikala.com/bigdata/karname/dummy-api
  newTag: 17686-master-9b2d1bee
