replicas:
- count: 1
  name: dummy-api
images:
- name: rm-bd-registry-01.bigdata.digikala.com/bigdata/karname/dummy-api
  newTag: 17660-dev-1ade35df
apiVersion: kustomize.config.k8s.io/v1beta1
patches:
- path: ingress-patch.yml
  target:
    kind: Ingress
    name: dummy-api

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - ./configs/.env
  - ./configs/config.yml
  name: dummy
  namespace: ki-dev-dummy

kind: Kustomization
namespace: ki-dev-dummy
resources:
- ../../application
